apiVersion: apps/v1
kind: Deployment # Create a deployment
metadata:
  name: postgres # Set the name of the deployment
spec:
  replicas: 1 # Set 3 deployment replicas
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:alpine3.17 # Docker image
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432 # Exposing the container port 5432 for PostgreSQL client connections.
          envFrom:
            - configMapRef:
                name: postgres-secret # Using the ConfigMap postgres-secret
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          #volumeMounts:
          #  - mountPath: /var/lib/postgresql/data
          #    name: postgresdata
      #volumes:
      #  - name: postgresdata
      #    persistentVolumeClaim:
      #      claimName: postgres-volume-claim